# Generated by Django 5.2.17 on 2026-09-10 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anuncio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Disponível"),
                            ("A", "Em andamento"),
                            ("I", "Indisponível"),
                        ],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cor", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Porte",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("porte", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Raca",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raca", models.CharField(max_length=100, unique=True)),
                (
                    "especie",
                    models.CharField(
                        choices=[("C", "Cachorro"), ("G", "Gato")], max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Adotante",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adotante",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conversa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "adotante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas",
                        to="petx.adotante",
                    ),
                ),
                (
                    "anuncio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversas",
                        to="petx.anuncio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "conversa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="petx.conversa",
                    ),
                ),
                (
                    "remetente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens_enviadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.CharField(blank=True, max_length=500)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(max_length=20, unique=True)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("data_nascimento", models.DateField()),
                ("ativo", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="adotante",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adotante",
                to="petx.perfil",
            ),
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin",
                        to="petx.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.CharField(blank=True, max_length=500)),
                ("nome", models.CharField(max_length=15)),
                (
                    "especie",
                    models.CharField(
                        choices=[("C", "Cachorro"), ("G", "Gato")],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("castrado", models.BooleanField(default=False)),
                ("vacinado", models.BooleanField(default=False)),
                ("sociavel", models.BooleanField(default=False)),
                ("nascimento", models.DateField()),
                ("descricao", models.CharField(max_length=1500)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Macho"), ("F", "Femea")], max_length=1
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Disponível"),
                            ("A", "Em andamento"),
                            ("I", "Indisponível"),
                        ],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "cor",
                    models.ManyToManyField(
                        blank=True, related_name="pets", to="petx.cor"
                    ),
                ),
                (
                    "porte",
                    models.ManyToManyField(
                        blank=True, related_name="pets", to="petx.porte"
                    ),
                ),
                (
                    "raca",
                    models.ManyToManyField(
                        blank=True, related_name="pets", to="petx.raca"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="anuncio",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anuncios",
                to="petx.pet",
            ),
        ),
        migrations.CreateModel(
            name="Preferencia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "especie",
                    models.CharField(
                        blank=True,
                        choices=[("C", "Cachorro"), ("G", "Gato")],
                        max_length=1,
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Macho"), ("F", "Femea")],
                        max_length=1,
                    ),
                ),
                ("castrado_sim", models.BooleanField(default=True)),
                ("castrado_nao", models.BooleanField(default=True)),
                ("vacinado", models.BooleanField(default=False)),
                ("sociavel", models.BooleanField(default=False)),
                ("idade", models.IntegerField(blank=True, null=True)),
                (
                    "adotante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias",
                        to="petx.adotante",
                    ),
                ),
                (
                    "cor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias",
                        to="petx.cor",
                    ),
                ),
                (
                    "porte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias",
                        to="petx.porte",
                    ),
                ),
                (
                    "raca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias",
                        to="petx.raca",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor",
                        to="petx.perfil",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pet",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="petx.tutor",
            ),
        ),
        migrations.AddField(
            model_name="anuncio",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anuncios",
                to="petx.tutor",
            ),
        ),
    ]
