# Generated by Django 5.2.17 on 2026-09-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petx", "0002_alter_admin_id_alter_adotante_id_alter_anuncio_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="pets/"),
        ),
    ]
