# Generated by Django 5.2.17 on 2026-09-10 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petx", "0003_alter_pet_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitacaoAdocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivo",
                    models.TextField(help_text="Por que você quer adotar este pet?"),
                ),
                (
                    "tem_experiencia",
                    models.BooleanField(
                        default=False, help_text="Já teve outros pets antes?"
                    ),
                ),
                (
                    "moradia",
                    models.CharField(
                        choices=[("CASA", "Casa"), ("APTO", "Apartamento")],
                        default="CASA",
                        max_length=4,
                    ),
                ),
                (
                    "outros_animais",
                    models.BooleanField(
                        default=False, help_text="Já tem outros animais em casa?"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "adotante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes",
                        to="petx.adotante",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes",
                        to="petx.pet",
                    ),
                ),
            ],
        ),
    ]
